baseurl: /
languageCode: en-US
title: Equitable Factor
theme: hugo-lithium
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: GitHub
      url: https://github.com/rstudio/blogdown
    - name: Twitter
      url: https://twitter.com/rstudio
      weight: 4
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: equitable_factor_logo_black.png
    width: 50
  footer: 
    branding: "&copy; Equitable Factor -- {Year}"
  socialIcons:
    - icon: "fa-brands fa-github"
      title: "GitHub"
      url: "https://github.com/lxndrblz/anatole/"
    - icon: "fa-brands fa-instagram"
      title: "instagram"
      url: "https://www.instagram.com/"
    - icon: "fa-solid fa-envelope"
      title: "e-mail"
      url: "mailto:mail@example.com"
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
